
version: 2

models:
  - name: sales_cleaned
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - sku
            - asin
