
version: 2

models:
  - name: fact_orderline
    description: "The orderline fact"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('dim_order')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: order_date
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_day
  - name: dim_order
    description: "The order dimension"
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
  - name: dim_product
    description: "The product dimension"
    columns:
      - name: product_id
        data_tests:
          - unique
          - not_null
